SET(_PF86 "PROGRAMFILES(X86)")
SET( FREETYPE_SEARCH_PATHS					# ASSIMP!
	./dependencies/freetype					# LINUX/MAC/UNIX
)

FIND_PATH( FREETYPE_INCLUDE_DIRS
	NAMES
		ft2build.h
	PATHS
		${FREETYPE_SEARCH_PATHS}
	PATH_SUFFIXES
		include
	DOC
		"The directory where assimp/mesh.h resides"
)

FIND_LIBRARY( FREETYPE_LIBRARIES
	NAMES
		freetype
	PATHS
		${FREETYPE_SEARCH_PATHS}
	PATH_SUFFIXES
		lib/x86
	DOC
		"The FREETYPE library"
)

# Check if we found it!
IF ( FREETYPE_INCLUDE_DIRS AND FREETYPE_LIBRARIES )
	SET( FREETYPE_FOUND TRUE )
	MESSAGE(STATUS "Looking for FREETYPE - found")
ELSE ( FREETYPE_INCLUDE_DIRS AND FREETYPE_LIBRARIES )
	SET( FREETYPE_FOUND FALSE )
	MESSAGE(STATUS "Looking for FREETYPE - not found")
ENDIF ( FREETYPE_INCLUDE_DIRS AND FREETYPE_LIBRARIES )